# v0.3 - 2025/09/27

##spring configuration
spring.datasource.url=jdbc:postgresql://cliembingdev-db.postgres.database.azure.com:5432/cliembing
spring.datasource.username=cliembing
spring.datasource.password=new1234!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


##logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

## swagger configuration

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

##security configuration
security.jwt.alg=HS256
security.jwt.ttl-seconds=36000
security.jwt.secret=jiwoongkingwangjjang5432godjiwoong

spring.security.user.name=cliembing
spring.security.user.password=1234

app.file.upload-root=/Users/jiwoongyang/Desktop/develop/cliembing/files
